In [1]:
import numpy as np

In [2]:
arr1 = np.array([11,21,31,41,49])

In [3]:
arr1

array([11, 21, 31, 41, 49])

In [4]:
arr2 = np.array([[1,9,21], [29,41,51], [58,72,8]])

In [5]:
arr2

array([[ 1,  9, 21],
       [29, 41, 51],
       [58, 72,  8]])

In [6]:
arr3 = np.array([[15,7,10,-11,20,75],[-3,9,24,1,100,-14]])

In [7]:
arr3

array([[ 15,   7,  10, -11,  20,  75],
       [ -3,   9,  24,   1, 100, -14]])

In [8]:
arr1.sum()

153

In [9]:
arr2.sum()

290

In [10]:
arr3.sum()

233

In [11]:
arr2.sum(axis=0)  #axis - 0 means row-wise addition

array([ 88, 122,  80])

In [12]:
arr2.sum(axis=1)  #axis = 1 means column-wise addition

array([ 31, 121, 138])

In [13]:
arr3.sum(axis=0)

array([ 12,  16,  34, -10, 120,  61])

In [14]:
arr2.sum(axis=1)

array([ 31, 121, 138])

In [15]:
np.average(arr1)

30.6

In [16]:
np.average(arr2)

32.22222222222222

In [17]:
np.average(arr3)

19.416666666666668

In [18]:
np.average(arr2, axis =1)

array([10.33333333, 40.33333333, 46.        ])

In [19]:
np.average(arr3, axis =1)

array([19.33333333, 19.5       ])

In [20]:
arr1.ndim

1

In [21]:
arr2.ndim

2

In [22]:
arr3.ndim

2

In [23]:
arr1.min()

11

In [24]:
arr2.min()

1

In [25]:
arr3.min(1)

array([-11, -14])

In [26]:
arr3.min(axis=1)

array([-11, -14])

In [27]:
arr1.max()

49

In [28]:
arr2.max()

72

In [29]:
arr3.max()

100

In [30]:
arr1.mean()

30.6

In [31]:
arr2.mean()

32.22222222222222

In [32]:
arr3.mean()

19.416666666666668

# Computation on Arrays : Broadcasting

In [33]:
# The term braodcasting refers to how numpy treats array with different dimensions
# While arithmetic operations leading to specific constraints. Moreover the smaller array is broadcasted over the larger array.
# so that they have compatible shapes.

In [34]:
a1 = np.array([1,3,7,5])
a2 = np.array([90,50,0,30])

In [35]:
c1 = a1 * a2

In [36]:
c1

array([ 90, 150,   0, 150])

In [37]:
d1 = 3

In [38]:
e1 = a1*3

In [39]:
e1

array([ 3,  9, 21, 15])

In [40]:
d1 = a1+3

In [41]:
d1

array([ 4,  6, 10,  8])

In [42]:
b1 = 4

In [43]:
c1 = a1 + b1

In [44]:
c1

array([ 5,  7, 11,  9])

In [45]:
arr4 = np.random.randint(10,50, size = (5,8))

In [46]:
arr4

array([[28, 10, 36, 10, 44, 27, 32, 33],
       [17, 16, 24, 22, 21, 43, 12, 46],
       [46, 29, 20, 44, 38, 30, 35, 37],
       [16, 27, 35, 25, 22, 41, 42, 19],
       [47, 11, 22, 44, 30, 24, 44, 19]])

In [47]:
# random function

# A two‐dimensional array is generated by the first array having a size of 5 rows and 
# columns, and the values are within 10 and 50

# A random three‐dimensional array of size 2*3*6 is generated by this second array. The
# generated random values are within 1 and 20

In [48]:
arr5 = np.random.randint(1,20, size = (2,3,6))  

In [49]:
arr5

array([[[ 3, 13,  8, 14, 12,  7],
        [ 9, 13,  3, 11,  9,  9],
        [ 2, 14,  3,  1, 18,  7]],

       [[ 5, 18, 17,  5, 11,  4],
        [11,  6,  4, 14,  6,  5],
        [ 4, 12,  7, 19, 18, 16]]])

In [50]:
arr5.ndim

3

In [51]:
a = np.array([0,2,3,0,1,6,5,2])

In [52]:
np.greater(a,2)

array([False, False,  True, False, False,  True,  True, False])

In [53]:
np.greater_equal(a,2)

array([False,  True,  True, False, False,  True,  True,  True])

In [54]:
np.less(a,2)

array([ True, False, False,  True,  True, False, False, False])

In [55]:
np.less_equal(a,2)

array([ True,  True, False,  True,  True, False, False,  True])

In [56]:
a = np.reshape(np.arange(25),(5,5))

In [57]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
greater_values = (a>10)

In [59]:
greater_values

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [60]:
even_values = (a%2==0)

In [61]:
even_values

array([[ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True],
       [False,  True, False,  True, False],
       [ True, False,  True, False,  True]])

In [62]:
b = ~(a%10 == 0)

In [63]:
b

array([[False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [False,  True,  True,  True,  True]])

In [64]:
c = (a%2==0) | (a%3==0)

In [65]:
c

array([[ True, False,  True,  True,  True],
       [False,  True, False,  True,  True],
       [ True, False,  True, False,  True],
       [ True,  True, False,  True, False],
       [ True,  True,  True, False,  True]])

# Masking in Numpy

In [66]:
# In numpy.ma.mask_rows() function, mask rows of a 2‐Dimensional array which hold masked values.
# The numpy.ma.mask_rows() function is a shortcut to mask_rowcols with axis equal to 0

In [67]:
import numpy as np
import numpy.ma as ma

In [68]:
array5 = np.zeros((4,4), dtype = int)

In [69]:
array5

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [70]:
array5[2,2] = 1

In [71]:
array5

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 0]])

In [72]:
array5 = ma.masked_equal(array5, 1)

In [73]:
array5

masked_array(
  data=[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, --, 0],
        [0, 0, 0, 0]],
  mask=[[False, False, False, False],
        [False, False, False, False],
        [False, False,  True, False],
        [False, False, False, False]],
  fill_value=1)

In [74]:
array5 = ma.mask_rows(array5)

In [75]:
array5

masked_array(
  data=[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [--, --, --, --],
        [0, 0, 0, 0]],
  mask=[[False, False, False, False],
        [False, False, False, False],
        [ True,  True,  True,  True],
        [False, False, False, False]],
  fill_value=1)

In [76]:
array5 = ma.mask_rowcols(array5)

In [77]:
array5

masked_array(
  data=[[--, --, --, --],
        [--, --, --, --],
        [--, --, --, --],
        [--, --, --, --]],
  mask=[[ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True],
        [ True,  True,  True,  True]],
  fill_value=1,
  dtype=int32)

In [78]:
arr_a1 = np.array([[1,9,21], [29,41,51], [58,72,8]])

In [79]:
arr_a1

array([[ 1,  9, 21],
       [29, 41, 51],
       [58, 72,  8]])

In [80]:
x = ma.masked_equal(arr_a1,58)

In [81]:
x

masked_array(
  data=[[1, 9, 21],
        [29, 41, 51],
        [--, 72, 8]],
  mask=[[False, False, False],
        [False, False, False],
        [ True, False, False]],
  fill_value=58)

In [82]:
y = ma.mask_rows(x)

In [83]:
y

masked_array(
  data=[[1, 9, 21],
        [29, 41, 51],
        [--, --, --]],
  mask=[[False, False, False],
        [False, False, False],
        [ True,  True,  True]],
  fill_value=58)

In [84]:
z = ma.mask_rowcols(x)

In [85]:
z

masked_array(
  data=[[--, 9, 21],
        [--, 41, 51],
        [--, --, --]],
  mask=[[ True, False, False],
        [ True, False, False],
        [ True,  True,  True]],
  fill_value=58)

# Fancy Indexing

In [134]:
# Fancy indexing is like the simple indexing, but we pass arrays of indices instead of single scalars 
# It permits us to quickly access as well as change complicated subsets of an array's values

# Exploring Fancy Indexing

# • Fancy indexing is conceptually simple which means passing an array of indices in order to access multiple array elements at one time

# • For instance, consider the below‐written array:

In [135]:
x = np.random.randint(100, size=10)

In [136]:
x

array([83, 24, 97, 39, 35, 44, 30, 38, 13,  2])

In [137]:
[x[3],x[7],x[2]]   #Normal indexing

[39, 38, 97]

In [138]:
x_fancy_index = [3,7,4]

In [139]:
x[x_fancy_index]

array([39, 38, 35])

In [140]:
ind2 = np.array([[3,7], [4,5]])

In [141]:
ind2

array([[3, 7],
       [4, 5]])

In [142]:
r = np.array([0,1])
c = np.array([0,1])
ind2[r,c]

array([3, 5])

In [143]:
y = np.arange(12).reshape((3,4))

In [144]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
row = np.array([0,1,2])
col = np.array([2,1,3])
y[row, col]

array([ 2,  5, 11])

In [146]:
y[row[:,np.newaxis], col]

array([[ 2,  1,  3],
       [ 6,  5,  7],
       [10,  9, 11]])

# Combined Indexing

In [147]:
y

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [148]:
y[2,[2,0,2]]

array([10,  8, 10])

In [149]:
y[2:,[2,0,3]]

array([[10,  8, 11]])

In [150]:
y[1:,[2,0,3]]

array([[ 6,  4,  7],
       [10,  8, 11]])

In [151]:
y[1,[2,0,3]]

array([6, 4, 7])

In [152]:
mask = np.array([1,0,1,0], dtype = bool)

In [153]:
mask

array([ True, False,  True, False])

In [154]:
y[row[:,np.newaxis], mask]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [155]:
a = np.arange(10)
i = np.array([2,1,8,4])
a[i] = 99
print(a)

[ 0 99 99  3 99  5  6  7 99  9]


In [156]:
a = np.arange(10)
i = np.array([2,1,8,4])
a[i] -= 1
print(a)

[0 0 1 3 3 5 6 7 7 9]


In [157]:
a = np.zeros(10)
a[[0,0]] = [2,8]
print(a)

[8. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [158]:
a = np.zeros(10)
a[[0,0]] = [2]
print(a)

[2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [159]:
a = np.zeros(10)
a[[1,2]] = [2,8]
print(a)

[0. 2. 8. 0. 0. 0. 0. 0. 0. 0.]


In [160]:
a = np.zeros(10)
a[[0,0]] = [8,23]
print(a)

[23.  0.  0.  0.  0.  0.  0.  0.  0.  0.]


In [161]:
a = np.zeros(10)
a[[1,2]] = [2,12]
print(a)

[ 0.  2. 12.  0.  0.  0.  0.  0.  0.  0.]


In [162]:
array = np.array([5,7,2,8])

In [163]:
print(np.sort(array))

[2 5 7 8]


In [164]:
print(np.sort(['pine-apple', 'banana', 'fig']))

['banana' 'fig' 'pine-apple']


In [165]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [166]:
a = np.sort(['pine-apple', 'banana', 'fig'])

In [167]:
a[::-1]

array(['pine-apple', 'fig', 'banana'], dtype='<U10')

In [169]:
array_sort_2d = np.array([[5,0,1],[9,3,6]])

In [171]:
x1 = np.sort(array_sort_2d)

In [172]:
x1

array([[0, 1, 5],
       [3, 6, 9]])

In [174]:
# ----------------------NumPy’s Structured Array-----------------------

# • Numpy’s Structured Array is similar to Struct in C programming language. 
# It is used in order to group data of different sizes and types

# • Data containers named as fields are used by the structured array. 
# Every data field can contain data of any size and type. With the help of dot notation, array elements can be accessed

# Structured Array Properties

# • All structs in the array have the similar number of fields

# • All structs have same fields names

# • For instance, consider a student's structured array with different fields such as year,name, and marks

# • Every record in array student has a structure of class Struct. 
# Moreover, the array of a structure is referred to as struct as adding any new fields 
# for a new struct in the array, contains the empty array

In [176]:
import numpy as np

In [177]:
a1 = np.array([('Stephen', 2022, 9.23), ('Masha', 2021, 8.13), ('Stefani', 2011, 9.76)], 
             dtype = [('name', (np.str_, 10)), ('year', np.int32), ('cgpa', np.float64)])

In [178]:
a1

array([('Stephen', 2022, 9.23), ('Masha', 2021, 8.13),
       ('Stefani', 2011, 9.76)],
      dtype=[('name', '<U10'), ('year', '<i4'), ('cgpa', '<f8')])

In [179]:
print(a1)

[('Stephen', 2022, 9.23) ('Masha', 2021, 8.13) ('Stefani', 2011, 9.76)]


In [180]:
b = np.sort(a1, order='name')

In [181]:
b

array([('Masha', 2021, 8.13), ('Stefani', 2011, 9.76),
       ('Stephen', 2022, 9.23)],
      dtype=[('name', '<U10'), ('year', '<i4'), ('cgpa', '<f8')])

In [182]:
z = np.sort(a1, order='cgpa')

In [185]:
z

array([('Masha', 2021, 8.13), ('Stephen', 2022, 9.23),
       ('Stefani', 2011, 9.76)],
      dtype=[('name', '<U10'), ('year', '<i4'), ('cgpa', '<f8')])

In [186]:
e = np.sort(a1, order='year')

In [188]:
e

array([('Stefani', 2011, 9.76), ('Masha', 2021, 8.13),
       ('Stephen', 2022, 9.23)],
      dtype=[('name', '<U10'), ('year', '<i4'), ('cgpa', '<f8')])

In [189]:
e[0]

('Stefani', 2011, 9.76)