In [1]:
import numpy as np

In [2]:
import pandas as pd

In [3]:
np.__version__

'1.20.3'

In [4]:
a = (1,2,3,4,5)
b = np.array(a)

In [5]:
print(b)
print(type(b))

[1 2 3 4 5]
<class 'numpy.ndarray'>


# Speed comparison : Numpy vs Core Python

In [6]:
import time as tm
time_python = tm.time()
print(time_python)

1670044572.8049645


In [7]:
import time as tm
import numpy as np
size_l = 100000

def pure_python_version():
    time_python = tm.time()
    list1 = range(size_l)
    list2 = range(size_l)
    sum_list = [list1[i]+list2[i] for i in range(len(list1))]
    return tm.time() - time_python

def numpy_version():
    time_numpy = tm.time()
    array1 = np.arange(size_l)
    array2 = np.arange(size_l)
    sum_array = array1 + array2
    return tm.time() - time_numpy

python_time = pure_python_version()
numpy_time = numpy_version()

print("pure python version=",format(python_time))  # To print an object during the run-time
print("numpy =",format(numpy_time))

pure python version= 0.022566556930541992
numpy = 0.0010027885437011719


In [8]:
import pandas as pd
import numpy as np
import time as tm

size_l = 100000

def core_python_version():
    time_python = tm.time()
    list1 = range(size_l)
    list2 = range(size_l)
    sum_list = [list1[i]+list2[i] for i in range(len(list1))]
    return tm.time() - time_python

def numpy_version():
    numpy_time = tm.time()
    array1 = np.arange(size_l)
    array2 = np.arange(size_l)
    sum_array = array1 + array2
    return tm.time() - numpy_time

python_time = core_python_version()
numpy_time = numpy_version()

print("Time elapsed for Core Python Version : ", python_time)
print("Time elapsed for Numpy Version : ", numpy_time)

Time elapsed for Core Python Version :  0.024632930755615234
Time elapsed for Numpy Version :  0.0009961128234863281


# Creating array

In [9]:
my_list = [1,2,3,4,5,6]
print(my_list)

[1, 2, 3, 4, 5, 6]


In [10]:
my_array = np.array(my_list)

In [11]:
my_array

array([1, 2, 3, 4, 5, 6])

In [12]:
array_2 = [[1,2,3,4],[4,5,6,7]]

In [13]:
array_2

[[1, 2, 3, 4], [4, 5, 6, 7]]

In [14]:
array_3 = np.array(array_2)

In [15]:
array_3

array([[1, 2, 3, 4],
       [4, 5, 6, 7]])

In [16]:
type(array_3)

numpy.ndarray

In [17]:
a = np.array([1,2,3,4,5,6], ndmin = 2)    

In [18]:
a

array([[1, 2, 3, 4, 5, 6]])

In [19]:
type(a)

numpy.ndarray

In [20]:
a = np.array([1,2,3,4,5,6], ndmin = 4)    

In [21]:
a

array([[[[1, 2, 3, 4, 5, 6]]]])

In [22]:
type(a)

numpy.ndarray

In [23]:
a = np.array([1,2,3,4,5,6], ndmin = 0)    

In [24]:
a

array([1, 2, 3, 4, 5, 6])

In [25]:
a.dtype

dtype('int32')

In [26]:
type(a)

numpy.ndarray

In [27]:
len(array_2)

2

In [28]:
list3 = [[1,2,3],[4,5,6],[7,8,9]]
array3 = np.array(list3)

In [29]:
array3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [30]:
array3[2][2]  #indexing 2nd element from 3rd row of the array

9

In [31]:
# Accessing the column
array3[:,1]  #Column 1 from all rows

array([2, 5, 8])

In [32]:
array3[2,:]  #All columns from the row 2

array([7, 8, 9])

In [33]:
array3[1:3,2:3]

array([[6],
       [9]])

In [34]:
array3[0:2,1:2]

array([[2],
       [5]])

# Array Attributes

In [35]:
array3.shape  #Returns Rows*Columns

(3, 3)

In [36]:
array3.ndim  #For checking dimension of array

2

# Array Initialization

In [37]:
array3.dtype

dtype('int32')

In [38]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [39]:
np.arange(1,11,3) #(start, end, space)

array([ 1,  4,  7, 10])

In [40]:
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [41]:
np.zeros((3,2), dtype =int)

array([[0, 0],
       [0, 0],
       [0, 0]])

In [42]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [43]:
np.ones((4,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [44]:
np.linspace(1,4,10) # (start, end, no. of values) -- Both start and stop are included  ---(4-1)/10 +............

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [45]:
np.linspace(3,4,10) # (start, end, no. of values) -- Both start and stop are included  ---(4-1)/10 +............

array([3.        , 3.11111111, 3.22222222, 3.33333333, 3.44444444,
       3.55555556, 3.66666667, 3.77777778, 3.88888889, 4.        ])

In [46]:
np.linspace(3,4,10).reshape(5,2)  #reshape(a,b) should be a multiple of 10(no. of values)

array([[3.        , 3.11111111],
       [3.22222222, 3.33333333],
       [3.44444444, 3.55555556],
       [3.66666667, 3.77777778],
       [3.88888889, 4.        ]])

In [47]:
np.eye(4,4) #Identity matrix -- all the elements in diagonal will be 1

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# Array Initialization with Random Numbers

In [48]:
np.random.rand(3)

array([0.16930247, 0.1010534 , 0.66635775])

In [49]:
np.random.rand(2) # Any random function between 0 to 1

array([0.22672201, 0.08976175])

In [50]:
np.random.randint(1,1000)

548

In [51]:
np.random.rand(9).reshape(3,3)

array([[0.66973732, 0.1495597 , 0.05362625],
       [0.04215358, 0.14143238, 0.6392841 ],
       [0.17623637, 0.81913509, 0.0206384 ]])

# Indexing arrays

In [52]:
array1 = [1,2,3,4,5,6]
array1

[1, 2, 3, 4, 5, 6]

In [53]:
array1[2]

3

In [54]:
array1[2:4]

[3, 4]

In [55]:
array1[-3:-1]

[4, 5]

In [56]:
array2 = np.array(array1)

In [57]:
array2

array([1, 2, 3, 4, 5, 6])

In [58]:
array2[2:4] = 9

In [59]:
array2

array([1, 2, 9, 9, 5, 6])

In [60]:
a = [[1,2,3],[4,5,6],[7,8,9]]
x = np.array(a)
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [61]:
x.min()

1

In [62]:
x.max()

9

In [63]:
x.mean()

5.0

In [64]:
x.argmin()

0

In [65]:
x.argmax()

8

In [66]:
x.sort()

In [67]:
x.reshape(9,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [68]:
x.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [69]:
x.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
x.transpose()

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

# Maths

In [71]:
import numpy as np
A = np.array([[4,10,11],[21,22,23],[31,32,33]])
B = np.ones((3,3))
print("Adding to Arrays : ")
print(A+B)
print("Subtracting to Arrays : ")
print(A-B)
print("Multiplication to Scalar : ")
print(3*A)
print("Matrix Multiplication : ")
print(np.dot(A,B))

Adding to Arrays : 
[[ 5. 11. 12.]
 [22. 23. 24.]
 [32. 33. 34.]]
Subtracting to Arrays : 
[[ 3.  9. 10.]
 [20. 21. 22.]
 [30. 31. 32.]]
Multiplication to Scalar : 
[[12 30 33]
 [63 66 69]
 [93 96 99]]
Matrix Multiplication : 
[[25. 25. 25.]
 [66. 66. 66.]
 [96. 96. 96.]]


In [72]:
a = np.array([[11.667,23.662], [33.21, 45.887]])
print(np.around(a))
print(np.around(a, decimals =1))
print(np.around(a, decimals =2))

[[12. 24.]
 [33. 46.]]
[[11.7 23.7]
 [33.2 45.9]]
[[11.67 23.66]
 [33.21 45.89]]


# Stats

In [73]:
A.sum()

187

In [74]:
A.mean()

20.77777777777778

In [75]:
np.std(A)

9.88576729757121

In [76]:
np.median(A)

22.0

In [77]:
np.mod(A,B)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [78]:
np.var(A)

97.72839506172839

# Binary Universal Functions

In [79]:
A = [[1,2,3],[3,4,5]]
B = [[3,3,4],[1,2,0]]
a = np.array(A)
b = np.array(B)
np.greater_equal(a,b)

array([[False, False, False],
       [ True,  True,  True]])

In [80]:
A = [[1,2,3],[3,4,5]]
B = [[3,3,4],[1,2,0]]
a = np.array(A)
b = np.array(B)
np.less_equal(a,b)

array([[ True,  True,  True],
       [False, False, False]])

In [81]:
np.less(a,b)

array([[ True,  True,  True],
       [False, False, False]])

In [82]:
np.less(b,a)

array([[False, False, False],
       [ True,  True,  True]])

# Subsetting Array

In [83]:
a

array([[1, 2, 3],
       [3, 4, 5]])

In [84]:
subset = a[:,1]=8

In [89]:
a

array([[1, 8, 3],
       [3, 8, 5]])

# Concatenating Array

In [109]:
A = [[1,2,3],[3,4,5]]
B = [[3,3,4],[1,2,0]]
a = np.array(A)
b = np.array(B)

In [111]:
np.concatenate([a,b], axis =1)

array([[1, 2, 3, 3, 3, 4],
       [3, 4, 5, 1, 2, 0]])

In [112]:
np.concatenate([a,b], axis =0)

array([[1, 2, 3],
       [3, 4, 5],
       [3, 3, 4],
       [1, 2, 0]])

# Reversing an array in Numpy

In [90]:
x = np.array([1,2,3,4,5,6,7,8,9])

In [91]:
x

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [92]:
y = np.flip(x)

In [93]:
y

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [94]:
a = np.array([1,2,3,4,5,6,7,8,9])

In [95]:
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [96]:
a[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [97]:
c = np.array([1,2,3,4,5,6,7,8,9])

In [98]:
d = np.flipud(c)

In [100]:
d

array([9, 8, 7, 6, 5, 4, 3, 2, 1])

In [101]:
z = np.array([[1,2,3], [4,5,6]])

In [102]:
z

array([[1, 2, 3],
       [4, 5, 6]])

In [103]:
t = np.flip(z)

In [104]:
t

array([[6, 5, 4],
       [3, 2, 1]])

In [105]:
f = np.array([[1,2,3], [4,5,6]])

In [106]:
f

array([[1, 2, 3],
       [4, 5, 6]])

In [107]:
g = np.flipud(f)

In [108]:
g

array([[4, 5, 6],
       [1, 2, 3]])